security:
    encoders:
        App\Entity\User:
            algorithm: auto

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_URL_SHORTENED_ALL

        ROLE_URL_SHORTENED_ALL:
            - ROLE_URL_SHORTENED_LIST
            - ROLE_URL_SHORTENED_CREATE
            - ROLE_URL_SHORTENED_READ
            - ROLE_URL_SHORTENED_UPDATE
            - ROLE_URL_SHORTENED_DELETE
            
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api/admin
            stateless: true
            provider: app_user_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator


    access_control:
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/admin,       roles: ROLE_ADMIN }