version: '3'

services:
  db:
    env_file:
      - ${APP_DIR}/.infra/docker/.env
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: ${DB_PROVIDER}:${DB_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${APP_DIR}/.infra/docker/build/data:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    networks: 
      net:
        aliases:
          - ${COMPOSE_PROJECT_NAME}.db
  
  www:
    env_file:
      - ${APP_DIR}/.infra/docker/.env
    build: 
      context: ./build/www
      args:
        - PHP_VERSION=${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-www
    command: ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
    tty: true
    links:
      - db:mysql
    volumes:
      - ${APP_DIR}:/var/www/html:cached
      - ${APP_DIR}/.infra/docker/build/logs:/var/log/apache2
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    networks:
      net:
        aliases:
          - ${COMPOSE_PROJECT_NAME}.www

  phpmyadmin:
    env_file:
      - ${APP_DIR}/.infra/docker/.env
    container_name: ${COMPOSE_PROJECT_NAME}-pma
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      net:
        aliases:
          - ${COMPOSE_PROJECT_NAME}.pma

networks: 
  net:
    driver: bridge
    ipam:
      config:
        - subnet: ${NET_IP}