#!/bin/bash

exec 1>&2

ROOT_PATH=$(git rev-parse --show-toplevel)
CHANGED_FILES=$(git diff --cached --name-status | awk '$1 != "D" { print $2 }')
CS=""

for FILE in $CHANGED_FILES ; do
    if [[ $FILE =~ ^src/.+\.(php|twig|yml|phtml)$ ]]; then
        CHANGE=$(php-cs-fixer fix $ROOT_PATH/$FILE --rules=@PSR2 --dry-run --using-cache=no | sed '$ d' | cut -d ')' -f 2)
        if [ ! -z "$CHANGE" ] ; then
            CS="$CS\n    $FILE"
        fi
    fi
done

if [ ! -z "$CS" ] ; then
    echo -e "The following files do not conform with FIG PSR-2:
$CS

Fix them in order to commit."
    for FILE in $CS ; do
        git reset $FILE
    done
    exit 1
fi

exit 0